### ISSUE TITLE
wait_status_ok中如果状态异常了退出，不用一直等待

### ISSUE THREAD

**Issue by landhu** [icaoda/wscloud-ui-issure-tracking#23]
[test_mongodb.py] 2019-02-13 17:30:51,776 page.trove.mongodb.backup.backup_page INFO -- create, wait backup bk0213_17303295 status...
[test_mongodb.py] 2019-02-13 17:30:57,358 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=正在创建
[test_mongodb.py] 2019-02-13 17:31:08,121 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:31:21,509 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:31:37,951 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:31:57,644 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:32:20,076 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:32:30,451 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:32:43,937 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:33:00,496 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:33:19,956 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:33:42,500 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:33:52,976 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:34:06,812 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:34:23,243 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:34:42,628 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:35:04,982 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:35:15,367 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:35:28,744 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:35:45,104 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:36:04,795 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:36:27,210 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:36:37,562 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败
[test_mongodb.py] 2019-02-13 17:36:50,980 page.trove.mongodb.backup.backup_page INFO -- instance bk0213_17303295 status=失败

**Comment by icaoda** [comment]
add 失败 status into wait_status_ok method
