### ISSUE TITLE
云硬盘快照页优化

### ISSUE THREAD

**Issue by landhu** [icaoda/wscloud-ui-issure-tracking#9]
![image](https://user-images.githubusercontent.com/22722402/48534156-22dd9500-e8e2-11e8-929c-3df2a3a481f3.png)

**Comment by icaoda** [comment]
原因:快照页面刷新机制:当快照页有某快照处于非终了状态,页面会主动刷新,重新渲染,直到全部为终了状态.
方案:快照页面后置条件增加等待,等待快照链中所有快照状态为终了状态再做其他动作.
